/**
 * @author Adriel Fabella
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JComboBox;

public class ConvertController {
	
	private ConvertView theView;
	private ConvertModel theModel;
	private String operation;
	
	public ConvertController(ConvertView theView, ConvertModel theModel){
		
			this.theView = theView;
			this.theModel = theModel;
			this.theView.addCalculationListener(new CalculateListener());
			this.theView.addButtonListener(new ButtonListener());
	}//end of contructor
	
	/**
	 * 2 Classes that implement the action listener
	 * Purpose: order has to start with the JComboBox, once selected, 
	 * the answer is generated by the result button based on the selectedItem of the Combo box
	 */
	
	class ButtonListener implements ActionListener{

		public void actionPerformed(ActionEvent e) {
			CalculateListener obj = new CalculateListener();
			double firstNumber = 0;
			
			String action = e.getActionCommand();
			if(action.equals("Result")){
				try{
							firstNumber = theView.getFirstNumber();
							
							switch(operation){
								case "Celsius to Fahrenheit" :
									theModel.celsiusToFahrenheit(firstNumber);
									theView.setCalcSolution(theModel.getConversionValue());
									break;
								case "Fahrenheit to Celsius" :
									theModel.fahrenheitToCelsius(firstNumber);
									theView.setCalcSolution(theModel.getConversionValue());
									break;
							}//switch
					}//try
					catch(Exception ex){
						theView.displayErrorMessage("Error! Insert an appropriate value!");
					}//catch
			}//if
			
		}//actionPerformed
	}//ButtonListener class
	
	class CalculateListener implements ActionListener{
		ButtonListener obj = new ButtonListener();
		
		public void actionPerformed(ActionEvent e) {			
			if(e.getSource() == theView.getOperationsList() ){
					JComboBox cb = (JComboBox)e.getSource();
					 operation = (String)cb.getSelectedItem();//get the operation chosen
					obj.actionPerformed(e);//call the result button listener
			}//if	
		}//actionPerformed()
		
	}//CalculateListener class
	
}//Global class
